### ISSUE TITLE
DFDC experiments results

### ISSUE THREAD

**Issue by Maisiechiu** [10Ring/LAA-Net#3]
Thanks for your awesome work! 

However, I have some questions about the cross-dataset experiment. 
In your paper, the experiment result of SBI[41] for DFDC is 86.15. But in SBI original paper, the AUC of 86.15 is for DFDCP. So, which dataset did you use in your paper? DFDC or DFDCP?

![image](https://github.com/user-attachments/assets/e2d2bbc9-a7fb-43d5-a121-b5800bde84a9)
![image](https://github.com/user-attachments/assets/90bb0a2c-5442-459e-92d0-0049477c9c2e)

**Comment by wuwuwuyue** [comment]
It looks like the DFDCP dataset

**Comment by 10Ring** [comment]
Hi @Maisiechiu Thanks for the question. It is DFDCP. We name it DFDC (as some other SOTA also did it) for a fair comparison. DFDCP is cited in the paper. Thanks.

**Comment by Maisiechiu** [comment]
Thanks for your reply.
